data = input('Type anything ')
print('The Primitive type of this value is ', type(data))
print('Only spaces? '    ,data.isspace())
print('Only spaces? '    ,data.isspace())
print('Numeric? '        ,data.isnumeric())
print('Alphabetic? '     ,data.isalpha())
print('Alphanumeric? '   ,data.isalnum())
print('Is upper? '       ,data.isupper())  
print('Is lower? '       ,data.islower())  
print('Is Capitalized? ' ,data.istitle())  
